- name: Setup personal SSH configuration
  hosts: localhost
  become: yes  # Use this if you need sudo privileges
  vars:
    user: 'vitya'    
    ssh_service_name: "{{ 'ssh' if ansible_distribution in ['Debian', 'Ubuntu'] else 'sshd' }}"

  tasks:
    - name: Ensure SSH authorized key is present
      authorized_key:
        user: "{{ user }}"
        state: present
        key: "empty1"  # Replace with the actual SSH key

    - name: Ensure SSH service is running
      service:
        name: "{{ ssh_service_name }}"
        state: started
        enabled: yes

    - name: Configure SSH server settings
      lineinfile:
        path: /etc/ssh/sshd_config
        line: "{{ item }}"
        state: present
        validate: '/usr/sbin/sshd -t -f %s'
      loop:
        - "Match User www-data"
        - "  ChrootDirectory %h"
        - "  ForceCommand internal-sftp"
        - "  PasswordAuthentication no"
        - "  AllowTcpForwarding no"
        - "  X11Forwarding no"
        - "Match User {{ user }}"
        - "  PasswordAuthentication yes"
        - "  AllowTcpForwarding yes"
        - "  X11Forwarding yes"
        - "PrintMotd no"
        - "StreamLocalBindUnlink yes"
        - "PasswordAuthentication yes"
        - "PermitRootLogin no"
        - "Port 356"

    - name: Restart SSH service to apply changes
      service:
        name: "{{ ssh_service_name }}"
        state: restarted
