---
- name: Configure software server
  hosts: all
  become: yes
  vars:
    user: 'vitya'
    pkgs:
      - apache2-utils
      - letsencrypt
      - certbot
      - python3-certbot-nginx
      - nginx
      - fail2ban
      - tcpdump
      - prometheus-node-exporter
    pkgs_uninst:
      - apache2-bin

  tasks:
    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      loop: "{{ pkgs }}"
      when: ansible_os_family == "Debian"

    - name: Uninstall unwanted packages
      apt:
        name: "{{ item }}"
        state: absent
      loop: "{{ pkgs_uninst }}"
      when: ansible_os_family == "Debian"

    - name: Install Docker
      apt:
        name: docker.io
        state: latest

    - name: Add user to Docker group
      user:
        name: "{{ user }}"
        groups: docker
        append: yes

    - name: Install Docker Compose plugin
      apt:
        name: docker-compose-plugin
        state: present

    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: latest

    - name: Ensure backup script is present
      copy:
        src: software/backup-pg.sh
        dest: /usr/bin/backup-pg.sh
        mode: '0755'
